CREATE TABLE users (
    user_id UUID PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    phone_number VARCHAR(20),
    username VARCHAR(255) UNIQUE,
    password_hash VARCHAR(255),
    date_of_birth DATE,
    gender VARCHAR(50),
    street_address VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(100),
    zip_code VARCHAR(20),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    barcode VARCHAR(255),
    is_active BOOLEAN DEFAULT TRUE,
    role VARCHAR(50),
    profile_picture VARCHAR(255),
    preferences JSON,
    last_login DATETIME,
    is_verified BOOLEAN DEFAULT FALSE,
    verification_token VARCHAR(255),
    failed_login_attempts INT DEFAULT 0
);
